# Use the official Node.js image as base
FROM node:20

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .
# Expose the port your app runs on
EXPOSE 3000

# Command to run your application
CMD ["node", "src/index.mjs"]
