version: '3.8'

services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=blog
      - MONGO_INITDB_ROOT_USERNAME=syedmoinuddin
      - MONGO_INITDB_ROOT_PASSWORD=moin1234 
    volumes:
      - 'mongodb_data:/data/db'

volumes:
  mongodb_data:
    driver: local
